name: Push
on:
  push:
    branches:
      - main
jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - uses: pulumi/actions@v3
        with:
          command: up
          stack-name: dev
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
      - run: |
          $Outputs = pulumi stack output -s dev -j | ConvertFrom-Json
          (pulumi stack output -s dev -C infra -j | ConvertFrom-Json).PSObject.Properties | % { 
            Write-Output "::set-output name=$($_.Name)::$($_.Value)" 
            "$($_.Name)=$($_.Value)" >> $env:GITHUB_ENV
          }
        shell: pwsh
        working-directory: infra
      - run: | 
          dotnet publish -c Release ./web/AppCatalog.Web.csproj
          Compress-Archive ./web/bin/Release/net6.0/publish/* ./web/bin/app.zip
          az login --service-principal -u $env:ARM_CLIENT_ID -p $env:ARM_CLIENT_SECRET --tenant $env:ARM_TENANT_ID
          az webapp deploy --resource-group ${{ env.ResourceGroupName }} --name ${{ env.AppServiceName }} --src-path ./web/bin/app.zip
        working-directory: app
        shell: pwsh
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      
